def build(bld):

    bld.program(
        source = [ 'mem_alloc.cpp' ],
        includes = [ '../include' ],
        target = 'mem_alloc',
        cxxflags = [ '-Wall', '-O3', '-g' ],
        linkflags = '-s',
        )

# vim: ft=python ai ts=4 sw=4 sts=4 et
